
import __ASTRO_IMAGE_IMPORT_2myHVG from "./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcustomizing-theme-color-schemes.md";
import __ASTRO_IMAGE_IMPORT_1xIVfm from "./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcustomizing-user-information.mdx";
import __ASTRO_IMAGE_IMPORT_rjybG from "./images/arharlem/harlembanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Far-harlem.mdx";
import __ASTRO_IMAGE_IMPORT_24IwCy from "./images/imggan/imageganbanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fimagegan.mdx";
import __ASTRO_IMAGE_IMPORT_Z2d2BwD from "./images/polxr/polxrbanner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpol-xr.mdx";
import __ASTRO_IMAGE_IMPORT_Z17oIBq from "./images/postag/postagbanner.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpos-tag.mdx";
import __ASTRO_IMAGE_IMPORT_ZKXYgj from "./images/emoverse/emoversebanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Femo-verse.mdx";
import __ASTRO_IMAGE_IMPORT_1qfjPv from "./images/gpt2probe/gpt2banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fprobing-gpt-2.mdx";
import __ASTRO_IMAGE_IMPORT_ZhliTl from "./images/hgr/hgrhandgesture.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhgr.mdx";
export default new Map([["./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcustomizing-theme-color-schemes.md", __ASTRO_IMAGE_IMPORT_2myHVG], ["./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcustomizing-user-information.mdx", __ASTRO_IMAGE_IMPORT_1xIVfm], ["./images/arharlem/harlembanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Far-harlem.mdx", __ASTRO_IMAGE_IMPORT_rjybG], ["./images/imggan/imageganbanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fimagegan.mdx", __ASTRO_IMAGE_IMPORT_24IwCy], ["./images/polxr/polxrbanner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpol-xr.mdx", __ASTRO_IMAGE_IMPORT_Z2d2BwD], ["./images/postag/postagbanner.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpos-tag.mdx", __ASTRO_IMAGE_IMPORT_Z17oIBq], ["./images/emoverse/emoversebanner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Femo-verse.mdx", __ASTRO_IMAGE_IMPORT_ZKXYgj], ["./images/gpt2probe/gpt2banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fprobing-gpt-2.mdx", __ASTRO_IMAGE_IMPORT_1qfjPv], ["./images/hgr/hgrhandgesture.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhgr.mdx", __ASTRO_IMAGE_IMPORT_ZhliTl]]);
		